apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: applications
  namespace: flux-system

spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/npalm/polar-deployment.git
  #ssh://git@github.com/npalm/polar-deployment
