spring:
  config:
    import: optional:configserver:,configtree:/workspace/secrets/*/
    #import: configserver:,configtree:/workspace/secrets/*/
  cloud:
    config:
      fail-fast: true
  datasource:
    url: jdbc:postgresql://polar-postgres.postgres.database.azure.com:5432/polardb_catalog
  rabbitmq:
    host: polar-rabbitmq.rabbitmq-system.svc.cluster.local
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ad73010d0b5c4cb5a8a8.northeurope.aksapp.io/auth/realms/PolarBookshop

logging:
  level:
    web: DEBUG
    org.springframeworksecurity: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: env, flyway, health, heapdump, info, prometheus
